DROP TABLE IF EXISTS Worker;
GO

CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME CHAR(25) NOT NULL,
    LAST_NAME CHAR(25),
    SALARY INT CHECK (SALARY BETWEEN 10000 AND 25000),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25) CHECK (DEPARTMENT IN ('HR', 'Sales', 'Accts', 'IT'))
);
GO

INSERT INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES (1, 'John', 'Doe', 20000, '2024-06-15', 'IT');

SELECT * FROM Worker;
